name: {{ cookiecutter.conda_env_name }}_dev
channels:
  - conda-forge

dependencies:
  # usefull and needed for all projects
  - python>=3.9
  - setuptools-scm   # automatic project numbering
  - ipykernel        # if you want jupyter to see your env
  - pip

  # for your project
  - numpy

  {% if cookiecutter.create_matplotlib_gallery -%}
  - cartopy
  - matplotlib
  {%- endif %}
  # - cython
  # - netCDF4
  # - xarray
  # - pandas

  # - matplotlib

  # - PyYAML
  # - zarr

  #### tests
  - pytest
  - pytest-cov
  - pytest-mpl

  #### doc
  - sphinx
  - pydata-sphinx-theme
  {% if cookiecutter.create_matplotlib_gallery -%}
  - sphinx-gallery
  {%- endif %}

  #### dev
  - black
  # - mypy
  - flake8
  - isort
  # - pre-commit
  # - pip:
  #   -
