name: TODO_env_name_dev
channels:
  - conda-forge

dependencies:
  # usefull and needed for all projects
  - python>=3.9
  - setuptools-scm   # automatic project numbering
  - ipykernel
  - pip

  # for your project
  - numpy
  - cython
  - netCDF4
  - PyYAML

  - matplotlib
  - zarr
  - pandas

  #### tests
  - pytest
  - pytest-cov
  - pytest-mpl

  #### doc
  - sphinx
  - pydata-sphinx-theme

  #### dev
  - black
  - mypy
  - flake8
  - isort
  # - pip:
  #   -
